[build-system]
requires = ["setuptools"]

[project]
name = "rproj"
version = "0.2.3"
description = "A simple project management tool"
license = "MIT"
dependencies = ["rich", "toml", "argparse", "appdirs"]

[project.scripts]
rproj = "rproj.main:main"
